helpers: Added dynamic symbol resolver
aquasecurity/libbpfgo pull request #128
Opened 2022-02-13 06:02 UTC by guyarb

Dynamic symbols are very important to attach u(ret)probe on common libraries such as openssl, libc, etc.

2022-02-15 16:30 UTC, grantseltzer commented on helpers/elf.go
> +func DynamicSymbolToOffset(path, symbol string) (uint32, error) {
What do you think about adding this logic to `SymbolToOffset` instead? If the named symbol isn't in the symbol table, check dynamic symbols. Is it possible to have a name collision?

2022-02-15 21:07 UTC, guyarb commented on helpers/elf.go
> +func DynamicSymbolToOffset(path, symbol string) (uint32, error) {
I'm in favor of your suggestion, I didn't want to "break" anyone using the original function, so ill change the code accordingly.

regarding the name collision - so the short answer would be yes, but it is only because the dynamic symbol table can contain exported functions that will appear in the regular symbol table.

a nice answer in stack overflow https://reverseengineering.stackexchange.com/a/21623

2022-02-15 21:12 UTC, guyarb commented on helpers/elf.go
> +func DynamicSymbolToOffset(path, symbol string) (uint32, error) {
created a simple SO (followed https://www.cprogramming.com/tutorial/shared-libraries-linux-gcc.html)
and checked both the regular symbol table and the dynamic symbol table
you can see the duplications
![image](https://user-images.githubusercontent.com/17148247/154149865-a342eaa2-ada9-4d63-8379-279b97b7d6ac.png)

2022-02-15 21:18 UTC, guyarb commented
> This is great, thank you! Just one comment, let me know what you think!

Thanks!
commented + fixed

2022-02-16 18:17 UTC, grantseltzer requested changes
Couple of small suggestions (let me know WYT) but otherwise LGTM!

2022-02-16 18:17 UTC, grantseltzer commented on helpers/elf.go
> +	return 0, errors.New("symbol not found")
```suggestion
	return 0, fmt.Errorf("symbol %s not found in %s", symbol, path)
```

2022-02-16 18:17 UTC, grantseltzer commented on helpers/elf.go
> +		return 0, fmt.Errorf("could not open symbol sections to resolve symbol offset: %w", regularSymbolsErr)
```suggestion
		return 0, fmt.Errorf("could not open symbol sections to resolve symbol offset: %w, %w", regularSymbolsErr, dynamicSymbolsError)
```

2022-02-16 18:35 UTC, grantseltzer commented on helpers/elf.go
> +		return 0, fmt.Errorf("could not open symbol sections to resolve symbol offset: %w, %w", regularSymbolsErr, dynamicSymbolsError)
```suggestion
		return 0, fmt.Errorf("could not open symbol sections to resolve symbol offset: %w, %w", regularSymbolsErr, dynamicSymbolsErr)
```

2022-02-16 18:37 UTC, grantseltzer approved these changes
I messed up that error name woops lol, thanks for the contribution!

2022-02-16 18:37 UTC, merged