Add helpers for passing flags
aquasecurity/libbpfgo pull request #154
Opened 2022-04-21 16:58 UTC by grantseltzer

The bpf helper `bpf_map_update_elem` takes a flags parameter which we're not letting users specify. Instead of breaking the API, i've added another helper for it. Additionally I've added API for the `bpf_map_lookup_elem_flags` helper.

Signed-off-by: grantseltzer <grantseltzer@gmail.com>

2022-04-27 05:49 UTC, kakkoyun submitted a review, later dismissed
LGTM :100:

2022-06-24 04:54 UTC, rafaeldtinoco commented on libbpfgo.go
> +func (b *BPFMap) UpdateFlags(key, value unsafe.Pointer, flags MapFlag) error {
The function name makes it look like it is updating the "flags" for a map, while actually we're just updating the map using flags argument. Should we change the method name ?

I think I'm ok with not breaking the API to have flags added, at least until we decide to break the API and unify those 2 (should we add a TODO at the code ?). Also, we could make Update() be a call to UpdateFlags() (with a new name) with a nil flag argument (something like libbpf does when deprecating functions).

2022-06-24 04:55 UTC, rafaeldtinoco requested changes
Code is good, I would re-think the function name, add a TODO and call one function from the other (unless you have better ideas, all ears).

2022-06-24 14:45 UTC, grantseltzer commented
Good thinking, I've updated accordingly.

2022-06-24 16:18 UTC, rafaeldtinoco approved these changes
LGTM. Make sure to "squashing" instead of "merging" (so we have a single commit). Thanks for addressing the suggestions.

2022-06-24 19:36 UTC, merged

2022-06-24 19:37 UTC, grantseltzer commented
I hate merging so much, that was an accident. It'l never happen again, I promise you!