Allow building on Linux < 6.1
aquasecurity/libbpfgo pull request #326
Opened 2023-05-04 07:42 UTC by saschagrunert

The latest release breaks build on lower kernel versions:

```
./libbpfgo.h:135:82: error: parameter 2 ('order') has incomplete type
  135 |                                                       enum bpf_cgroup_iter_order order,
      |                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
./libbpfgo.h: In function 'bpf_iter_attach_opts_new':
./libbpfgo.h:148:10: error: 'union bpf_iter_link_info' has no member named 'cgroup'
  148 |     linfo->cgroup.order = order;
      |          ^~
./libbpfgo.h:149:10: error: 'union bpf_iter_link_info' has no member named 'cgroup'
  149 |     linfo->cgroup.cgroup_fd = cgroup_fd;
      |          ^~
./libbpfgo.h:150:10: error: 'union bpf_iter_link_info' has no member named 'cgroup'
  150 |     linfo->cgroup.cgroup_id = cgroup_id;
      |          ^~
./libbpfgo.h:151:10: error: 'union bpf_iter_link_info' has no member named 'task'
  151 |     linfo->task.tid = tid;
      |          ^~
./libbpfgo.h:152:10: error: 'union bpf_iter_link_info' has no member named 'task'
  152 |     linfo->task.pid = pid;
      |          ^~
./libbpfgo.h:153:10: error: 'union bpf_iter_link_info' has no member named 'task'
  153 |     linfo->task.pid_fd = pid_fd;
      |          ^~) (typecheck)
```

We now pre-check the kernel version to allow builds on older systems as well.

Refers to https://github.com/kubernetes-sigs/security-profiles-operator/pull/1663

2023-05-04 09:17 UTC, rafaeldtinoco commented
Thank you, will merge it shortly. @yanivagman we should fix this, release a new version and bump in tracee as well (for the fix release) I'll include 6.1 and 6.2 kernels in testing.

2023-05-04 11:41 UTC, mozillazg commented
> The latest release breaks build on lower kernel versions:
> 
> ```
> ./libbpfgo.h:135:82: error: parameter 2 ('order') has incomplete type
>   135 |                                                       enum bpf_cgroup_iter_order order,
>       |                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
> ./libbpfgo.h: In function 'bpf_iter_attach_opts_new':
> ./libbpfgo.h:148:10: error: 'union bpf_iter_link_info' has no member named 'cgroup'
>   148 |     linfo->cgroup.order = order;
>       |          ^~
> ./libbpfgo.h:149:10: error: 'union bpf_iter_link_info' has no member named 'cgroup'
>   149 |     linfo->cgroup.cgroup_fd = cgroup_fd;
>       |          ^~
> ./libbpfgo.h:150:10: error: 'union bpf_iter_link_info' has no member named 'cgroup'
>   150 |     linfo->cgroup.cgroup_id = cgroup_id;
>       |          ^~
> ./libbpfgo.h:151:10: error: 'union bpf_iter_link_info' has no member named 'task'
>   151 |     linfo->task.tid = tid;
>       |          ^~
> ./libbpfgo.h:152:10: error: 'union bpf_iter_link_info' has no member named 'task'
>   152 |     linfo->task.pid = pid;
>       |          ^~
> ./libbpfgo.h:153:10: error: 'union bpf_iter_link_info' has no member named 'task'
>   153 |     linfo->task.pid_fd = pid_fd;
>       |          ^~) (typecheck)
> ```
> 
> We now pre-check the kernel version to allow builds on older systems as well.
> 
> Refers to [kubernetes-sigs/security-profiles-operator#1663](https://github.com/kubernetes-sigs/security-profiles-operator/pull/1663)

IMHO, the error may be due to an old version of libbpf. Could you please try upgrading the libbpf version to v1.2.0 and then try again?

2023-05-04 12:05 UTC, saschagrunert commented
@mozillazg I did that in the linked PR, for example this test is using libbpf v1.2.0: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_security-profiles-operator/1663/pull-security-profiles-operator-build/1654022636025417728/build-log.txt

2023-05-04 18:24 UTC, rafaeldtinoco commented
> AFAIK the environment we use to compile Tracee doesn't have a kernel newer than 6.0

True, I had a quick look when I said that. Thought it was the opposite. Will try to reproduce and check (and also add 6.1 and 6.2 to our tests).

2023-05-04 18:27 UTC, rafaeldtinoco reviewed
Still checking...

2023-05-04 18:27 UTC, rafaeldtinoco commented on libbpfgo.h
>  #include <linux/bpf.h> // uapi
libbpfgo should not depend on UAPI afaik, that was the recent change/fix I did for selftests, failing for UAPI dependencies. And, that is exactly the problem here. This type should be declared in a "vmlinux.h" like file and, if thats the case, have different flavors of the type per kernel version (so libbpf relocations can work).

2023-05-04 18:29 UTC, rafaeldtinoco commented on libbpfgo.h
>  #include <linux/bpf.h> // uapi
fix done for the selftests: https://github.com/aquasecurity/libbpfgo/commit/99ea32d09a1e8ca9ba644a73ac73dcc32c6424f9

2023-05-05 04:14 UTC, rafaeldtinoco commented
@saschagrunert I think I know what is wrong. We're able to compile in all kernel versions because the UAPI headers we use for building, both, libbpfgo AND tracee, use the UAPI headers that come with libbpf itself.

Compare this:

https://github.com/kubernetes-sigs/security-profiles-operator/pull/1663/files#diff-7e35579e713a6b96ffa0fbd1fc147e020cc06b4b09d5c9cecafc5803febcaca0R23

With:

https://github.com/aquasecurity/libbpfgo/blob/0238ec325a967ca48d8958f449e236b5bc432263/Makefile/#L51-L55

and

https://github.com/aquasecurity/tracee/blob/d42f9703689e3661a6f197da889080c638ebfb05/Makefile#L319-L328

And you can see that in both, libbpfgo and tracee, we use "install_uapi_headers" makefile target from the embedded libbpf (and you should do the same I believe).

With that, this patch isn't needed nor wanted, right ?

2023-05-05 04:17 UTC, rafaeldtinoco requested changes
-1 unless my last comment has some miss conception of what is going on.

2023-05-05 06:33 UTC, saschagrunert commented
Alright, thank you for the hint @rafaeldtinoco! Closing this one now.

2023-05-05 06:33 UTC, closed without merging