feat: AddRingBuf() using ring_buffer__add
aquasecurity/libbpfgo pull request #430
Opened 2024-05-20 06:07 UTC by mighty1231

libbpf provides ring_buffer__add to handle multiple ringbufs

- implements AddRingBuf() for ring_buffer__add wrapper
- single RingBuffer object now handles multiple slots
- update ringbuffers selftest to show how to handle multiple ringbuf

Reference
- https://github.com/torvalds/linux/blob/eb6a9339efeb6f3d2b5c86fdf2382cdc293eca2c/tools/testing/selftests/bpf/progs/test_ringbuf_multi.c
- https://github.com/torvalds/linux/blob/eb6a9339efeb6f3d2b5c86fdf2382cdc293eca2c/tools/testing/selftests/bpf/prog_tests/ringbuf_multi.c#41

2024-05-20 06:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/libbpfgo?pullRequest=430) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/libbpfgo?pullRequest=430) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/libbpfgo?pullRequest=430) it.</sub>

2024-05-21 19:22 UTC, geyslan commented
@mighty1231 tks for this PR. There's a formatting issue https://github.com/aquasecurity/libbpfgo/pull/430/checks. As it is solved I'll stash it for later review. Tks again.

2024-05-22 02:49 UTC, mighty1231 commented
@geyslan I ran `make fmt-fix`. Now `make fmt-check` returns no error

2024-05-28 01:10 UTC, mighty1231 commented
Failed test `map-getmapsbyname` seems not related to my PR, because it seems don't use any ringbuffer, and it runs before the `ringbuffers` test.

2024-05-28 17:50 UTC, geyslan commented
@mighty1231, I suspect that self-test/iter sometimes fails due to ping usage and internal network malfunction. Well, it seems like a flaky test.

2024-06-06 21:04 UTC, geyslan requested changes
@mighty1231 I tested it and it works nice. That's awesome.

I would just ask you to make the selftest more robust, since you have touched the logic of the slot (index) inside RingBuffer that's used by `rwArray` which .

Would you mind to improve the the respective selftest to submit a greater volume of data through a greater number of slots (ringbuffers) not reusing the same data holder? I mean, try using more than one program to submit the data.

2024-06-10 00:49 UTC, mighty1231 commented
> @mighty1231 I tested it and it works nice. That's awesome.
> 
> I would just ask you to make the selftest more robust, since you have touched the logic of the slot (index) inside RingBuffer that's used by `rwArray` which .
> 
> Would you mind to improve the the respective selftest to submit a greater volume of data through a greater number of slots (ringbuffers) not reusing the same data holder? I mean, try using more than one program to submit the data.

I am confused. What did you mean among following tests?

1. More tests to check thread safety of `Module *AddRingBuf()`, `RingBuffer *Stop()`, and `RingBuffer *Close()`
2. More tests with two or more `struct *RingBuffer` in golang
3. More tests wtih two or more `NewModuleFromFile("main.bpf.o")` call
4. More tests wtih two or more probes - other than `kprobe__sys_mmap` from `selftest/ringbuffers/main.bpf.c`

1 may be resolved with notifying the limitation for users. 2 - The motivation of this PR. I have got completely lost to use more than one RingBuffer, so I decided to use `ring_buffer__add`. And, it's difficult to guess what can be improved by case 3 and 4

2024-06-10 01:00 UTC, mighty1231 commented on libbpfgo.c
> +        return ret;
I changed it.

2024-06-10 11:08 UTC, geyslan commented
>     5. Make similar to ringbuf_multi test from linux repository

It would be awesome to have a huge amount of tests like ringbuf_multi. Anyway, I think it would take longer.

I meant:

- increasing `numberOfEvent*Received*` to a considerable amount.
- split the `recvLoop` `for` `select` into the amount of ringbuf slots, raising one goroutine for each.

2024-06-11 00:38 UTC, mighty1231 commented
I don't know how to split the for-select loop, and I didn't understand what is improved with new test.

2024-06-13 13:03 UTC, geyslan commented
@NDStrahilevitz do you mind reviewing this?

2024-06-26 12:56 UTC, geyslan commented
@mighty1231 I'm merging this. Thanks again for your contrib.

2024-06-26 12:57 UTC, merged